apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7pmv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-7pmv@sha256:1f199803173ed51a5825a659e67d77f3565d365a7b279b16705cc96f2e07f99a
        name: my-nodejs
        resources: {}
status: {}
